version: '3.8'

volumes:
  db:
    driver: local

networks:
  freeport:
    external: true

  api:
    container_name: freeport-coinprices
    image: freeport/freeport-coinprices
    restart: on-failure
    build:
        context: ./
        dockerfile: Dockerfile
    volumes:
        - ./:/app
    ports:
      - '6025:6025'
    networks:
      - freeport
